### ISSUE TITLE
iPad Pro + Enum support?

### ISSUE THREAD

**Issue by Jules2010** [squarefrog/UIDeviceIdentifier#11]
Please add iPad Pro constant.

Also it would be awesome if this returned an enum value or constant.

Good job.

**Comment by squarefrog** [comment]
iPad Pro added in https://github.com/squarefrog/UIDeviceIdentifier/commit/282e4ecc7dbd6eee50b345d440690f41641a13e5

Returning an enum is not a bad idea, would be a breaking change though.
