### ISSUE TITLE
platformString cause `message sent to deallocated instance`

### ISSUE THREAD

**Issue by paulz** [squarefrog/UIDeviceIdentifier#17]
Subsequent calls to platformString cause crash due to deallocated instance of NSDictionary.

Here is a [Quick](https://github.com/Quick/Quick) spec to reproduce the issue:
```
import Quick
import Nimble
import UIDeviceIdentifier

class UIDeviceHardwareSpec : QuickSpec {
    override func spec() {
        context("platformString") {
            it("should not crash with message sent to deallocated instance") {
                var platform : String?
                autoreleasepool {
                    platform = UIDeviceHardware.platformString()
                }
                autoreleasepool {
                    platform = UIDeviceHardware.platformString()
                }
                expect(platform).notTo(beNil())
            }
        }
    }
}
```

**Comment by squarefrog** [comment]
It works fine here?

```
10:47:51.608 TestUIDevice[37008:2553840] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
10:47:51.616 TestUIDevice[37008:2553836] _IDE_startExecutingTestPlanWithProtocolVersion:16
Test Suite 'All tests' started at 2015-12-21 10:47:51.624
Test Suite 'Quick.framework' started at 2015-12-21 10:47:51.625
Test Suite 'Quick.framework' passed at 2015-12-21 10:47:51.626.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'TestUIDeviceTests.xctest' started at 2015-12-21 10:47:51.627
Test Suite 'UIDeviceHardwareSpec' started at 2015-12-21 10:47:51.627
Test Case '-[TestUIDeviceTests.UIDeviceHardwareSpec platformString__should_not_crash_with_message_sent_to_deallocated_instance_UserspiDesktopTestUIDeviceTestUIDeviceTestsUIDeviceTestsswift_8]' started.
Test Case '-[TestUIDeviceTests.UIDeviceHardwareSpec platformString__should_not_crash_with_message_sent_to_deallocated_instance_UserspiDesktopTestUIDeviceTestUIDeviceTestsUIDeviceTestsswift_8]' passed (0.002 seconds).
Test Suite 'UIDeviceHardwareSpec' passed at 2015-12-21 10:47:51.631.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.003) seconds
Test Suite 'TestUIDeviceTests.xctest' passed at 2015-12-21 10:47:51.631.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.005) seconds
Test Suite 'All tests' passed at 2015-12-21 10:47:51.632.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.008) seconds


Test session log:
	/var/folders/32/xpgz1xvx7d143gv432kxyhtw0000gn/T/com.apple.dt.XCTest-status/Session-2015-12-21_10:47:47-jgGLYw.log
```

**Comment by squarefrog** [comment]
Never mind - managed to reproduce in a test app! Thanks for the report, fixed in `1.0.1`.

Please update using: `$ pod update UIDeviceIdentifier`

**Comment by Coeur** [comment]
@squarefrog did you try `__strong static const NSDictionary *platformStrings;` instead?

**Comment by paulz** [comment]
Yes, it did not work for me either.

**Comment by Coeur** [comment]
The test case provided shows an `autoreleasepool{}`, so isn't it the inherent danger of using the value outside of the pool?

**Comment by Coeur** [comment]
@paulz if you find an explanation: http://stackoverflow.com/questions/34406975/singleton-pattern-for-static-const-id-results-in-deallocated-instance

**Comment by squarefrog** [comment]
The test case didn't exhibit the crashing behaviour for me. However creating a simple demo project with a button that printed a string did when I spammed the button in quick succession. I didn't use an `autoreleasepool` in that demo project. 

Using the singleton pattern may be premature optimisation. Personally I'd called `platformString` once and store the value in a variable, but it's definitely worth protecting against people who do not.

**Comment by Coeur** [comment]
So Paulz's example is not reproducible. May I have your demo project? Because it a static var being deallocated makes no sense.

**Comment by squarefrog** [comment]
Sure - the project is available [on dropbox](https://dl.dropboxusercontent.com/u/2063716/TestUIDevice.zip). Check the `Podfile` first as the `UIDeviceIdentifier` pod is currently pointing to a local directory.

**Comment by Coeur** [comment]
I found this in your podspec:

    s.requires_arc = false

This results in UIDeviceHardware.m to be compiled without ARC.
This results in any static var to be `unretained` instead of `strong`.

Keep the singleton, but either change to " s.requires_arc = true" or add `[platformStrings retain]`.
