### ISSUE TITLE
CocoaPods still list 1.0.3

### ISSUE THREAD

**Issue by kawanet** [squarefrog/UIDeviceIdentifier#29]
Please do `git tag 1.1.1 && git push --tags && pod trunk push` or something to publish 1.1.1.

https://cocoapods.org/pods/UIDeviceIdentifier

**Comment by squarefrog** [comment]
I'll look into that tomorrow. In the mean time though you can always point the pod file at `HEAD`. 

There will never be any more breaking changes, only maintenance so no real risk from using the head of master.

**Comment by Coeur** [comment]
And if you don't know the syntax for getting latest:
`pod 'UIDeviceIdentifier', :git => 'https://github.com/squarefrog/UIDeviceIdentifier'`

**Comment by squarefrog** [comment]
Version 1.1.1 has now been pushed. I did notice that the `README` files recommendation is to use the above line in your podfile.

https://github.com/squarefrog/UIDeviceIdentifier#podfile-inclusion
