### ISSUE TITLE
cocoapod version did not update

### ISSUE THREAD

**Issue by hbcffc** [squarefrog/UIDeviceIdentifier#31]
Current cocoa pods version 1.1.1 don't have iPhone8 and iPhone X.

**Comment by hbcffc** [comment]
Just a friendly reminder.

**Comment by squarefrog** [comment]
Please follow the instructions as listed in the readme, particularly this line:

    pod 'UIDeviceIdentifier', :git => 'https://github.com/squarefrog/UIDeviceIdentifier.git'

That way you don't have to worry about version numbers. I will make a new number when I can though!
