### ISSUE TITLE
Lost support for iPhone11,6 

### ISSUE THREAD

**Issue by TYM1** [squarefrog/UIDeviceIdentifier#35]
Lost support for iPhone11,6

**Comment by squarefrog** [comment]
I’m sorry, can you be a bit more specific please?

**Comment by Coeur** [comment]
@squarefrog : We added iPhone11,2 + iPhone11,4 + iPhone11,8.
He's telling we're missing identification for 11,6. And I could add that we're missing identification for 11,1, 11,3, 11,5 and 11,7. But it's not easy to tell which devices they are.

**Comment by squarefrog** [comment]
Ok that makes sense. I’ll do so digging.

**Comment by Coeur** [comment]
Not an official source, but according to Hannes Sverrisson on https://stackoverflow.com/a/52412893/1033581:
>    // 2018 models
    if ([platform isEqualToString:@"iPhone11,1"])    return @"iPhone XS (GSM+CDMA)";
    if ([platform isEqualToString:@"iPhone11,2"])    return @"iPhone XS (GSM)";
    if ([platform isEqualToString:@"iPhone11,4"])    return @"iPhone XS Max (GSM+CDMA)";
    if ([platform isEqualToString:@"iPhone11,6"])    return @"iPhone XS Max (GSM)";
    if ([platform isEqualToString:@"iPhone11,8"])    return @"iPhone XR (GSM+CDMA)";
    if ([platform isEqualToString:@"iPhone11,9"])    return @"iPhone XR (GSM)";

We could eventually extrapolate to 11,1/2/3 being XS variants, 11,4/5/6 being XS Max variants and 11,7/8/9 being XR variants.

**Comment by Coeur** [comment]
A kind of reliable source is https://www.theiphonewiki.com/wiki/Models, and it lists (alphabetically):
* iPhone XR is iPhone11,8
* iPhone XS is iPhone11,2
* iPhone XS Max is iPhone11,4
* iPhone XS Max CHINA is iPhone11,6

**Comment by squarefrog** [comment]
Thanks Antoine. I'll add these now, however, I don't think we can add the XR yet, as there isn't any definite proof of the model number. 

As a side note, I have been wondering if there is significant benefit to including Cellular differences (GSM+CDMA, GSM, etc)? Personally I dont care about the cellular differences, but interested in what the community wonders.

**Comment by squarefrog** [comment]
This is now merged in tag [1.1.4](https://github.com/squarefrog/UIDeviceIdentifier/tree/1.1.4).

I verified this Xcode 10's devices data base: 

    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/standalone/device_traits.db

Its fair to assume that this is reasonably accurate. The `iPhone xx` has piqued my interest though!

**Comment by Coeur** [comment]
`iPhone xx` was likely the codename of the XS or XR during before launch.

**Comment by squarefrog** [comment]
Probably, but the conspiracy theorist in me wonders why it has the same platform identifier as the 7/7+.
