### ISSUE TITLE
Would you like to update for the new iPhone 11 / iPhone 11 Pro / iPhone 11 Pro Max?

### ISSUE THREAD

**Issue by pcjbird** [squarefrog/UIDeviceIdentifier#38]
Hello, would you like to update for the new iPhone 11 / iPhone 11 Pro / iPhone 11 Pro Max?

**Comment by squarefrog** [comment]
This is now done. In future it may be quicker to just submit a pull request rather than raising an issue.

**Comment by pcjbird** [comment]
I got it, thanks. Next time I'd like to submit a pull request.

**Comment by squarefrog** [comment]
I’m sorry if that sounded blunt. I didn’t mean to be.  I found a [great gist](https://gist.github.com/adamawolf/3048717) here that seems to be regularly updated.
