### ISSUE TITLE
1.4.0 issues

### ISSUE THREAD

**Issue by hengyizhangcn** [squarefrog/UIDeviceIdentifier#39]
The platforms supported were modified from version 1.3.0 in `UIDeviceIdentifier.podspec`, like:
```s.platforms     = { :ios => nil, :tvos => nil }```
to version 1.4.0, like:
```
 s.ios.deployment_target = ""
 s.tvos.deployment_target = ""
```
This changed can lead to the not support for architecture armv7 when archiving by Xcode 11.x.

**Comment by squarefrog** [comment]
Sorry about that. This is mostly a community effort now, so I don't check with older Xcodes/targets. The minimum target now is 9.0.
