### ISSUE TITLE
Fall 2021 Models Release?

### ISSUE THREAD

**Issue by jablair** [squarefrog/UIDeviceIdentifier#46]
Was version 1.7.0 supposed to contain the model name updates from https://github.com/squarefrog/UIDeviceIdentifier/pull/45?

I just noticed the change flow into one of my apps via `pod install`, except it only had the changes from https://github.com/squarefrog/UIDeviceIdentifier/pull/43. Got a little confused why a readme-only change from July suddenly decided to show up. Any chance the `1.7.0` had previously been created for the SPM support?

**Comment by squarefrog** [comment]
Yeah probably. Just checked and the tag is pointing at the wrong commit. I’ll push 1.7.1 later, but I’d recommend pointing your podfile at the master branch then you don’t have to wait for a podfile to get pushed

**Comment by squarefrog** [comment]
All done now. You should be able to find v1.7.1 if you update pod trunk.
