### ISSUE TITLE
Xcode13.1 iOS12 crash

### ISSUE THREAD

**Issue by ChenPingSheng** [squarefrog/UIDeviceIdentifier#47]
Use this pod in Xcode13.1, run on iOS12，App will crash.
![截屏2021-12-14 上午11 22 25](https://user-images.githubusercontent.com/14194096/145927353-059e58a8-6525-4f2c-8794-b379a5bc9fe4.png)
Specify s.ios.deployment_target to 6.0 or any other version, can avoid crash.

**Comment by squarefrog** [comment]
Would you like to submit a pull request?

**Comment by ChenPingSheng** [comment]
I have submit a pull request: https://github.com/squarefrog/UIDeviceIdentifier/pull/48
Please review it.

**Comment by squarefrog** [comment]
Thanks, merges and pushed as v2.0.0
